# Generated by Django 5.0.14 on 2026-06-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusternode',
            name='disk_io_delay_ms',
            field=models.FloatField(blank=True, help_text='节点级 I/O 延迟（毫秒），从 diskstat 汇总', null=True, verbose_name='I/O延迟(ms)'),
        ),
        migrations.AddField(
            model_name='clusternode',
            name='diskstat',
            field=models.JSONField(blank=True, default=list, help_text='每个磁盘设备的 I/O 统计，如 [{"dev":"sda","read":123,"write":456,"read_ios":10,"write_ios":20,"io_ms":50}]', verbose_name='磁盘I/O统计'),
        ),
    ]
