# Generated by Django 5.0.14 on 2026-06-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0001_initial'),
        ('clusters', '0003_pve_fields_required'),
        ('scanner', '0002_clusternode_disk_io_delay_ms_clusternode_diskstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='HAResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(help_text='vm:101 / ct:201', max_length=64, verbose_name='资源ID')),
                ('resource_type', models.CharField(help_text='vm / ct', max_length=16, verbose_name='类型')),
                ('vmid', models.IntegerField(blank=True, null=True, verbose_name='VM/CT ID')),
                ('node_name', models.CharField(blank=True, max_length=128, verbose_name='所在节点')),
                ('state', models.CharField(blank=True, help_text='started / stopped / ...', max_length=32, verbose_name='状态')),
                ('ha_group', models.CharField(blank=True, max_length=64, verbose_name='HA组')),
                ('ha_status', models.CharField(blank=True, help_text='active / inactive / ...', max_length=32, verbose_name='HA状态')),
                ('crm_state', models.CharField(blank=True, help_text='started / stopped / ...', max_length=32, verbose_name='CRM状态')),
                ('max_restarts', models.IntegerField(blank=True, null=True, verbose_name='最大重启次数')),
                ('max_shutdown', models.IntegerField(blank=True, null=True, verbose_name='最大关机时间')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ha_resources', to='clusters.cluster', verbose_name='所属集群')),
            ],
            options={
                'verbose_name': 'HA资源',
                'verbose_name_plural': 'HA资源',
                'ordering': ['sid'],
            },
        ),
        migrations.CreateModel(
            name='LXCConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=256, verbose_name='主机名')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='CPU核心数')),
                ('memory_mb', models.IntegerField(blank=True, null=True, verbose_name='内存(MB)')),
                ('swap_mb', models.IntegerField(blank=True, null=True, verbose_name='Swap(MB)')),
                ('os_type', models.CharField(blank=True, max_length=64, verbose_name='系统类型')),
                ('rootfs', models.JSONField(blank=True, default=dict, help_text='{"storage":"local-lvm","size":"8G"}', verbose_name='根文件系统')),
                ('mount_points', models.JSONField(blank=True, default=list, verbose_name='挂载点')),
                ('net_devices', models.JSONField(blank=True, default=list, help_text='[{"slot":"net0","name":"eth0","bridge":"vmbr0","hwaddr":"...","ip":"dhcp"}]', verbose_name='网卡')),
                ('ha_enabled', models.BooleanField(default=False, verbose_name='HA启用')),
                ('ha_group', models.CharField(blank=True, max_length=64, verbose_name='HA组')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('tags', models.CharField(blank=True, max_length=256, verbose_name='标签')),
                ('startup_order', models.CharField(blank=True, max_length=64, verbose_name='启动顺序')),
                ('raw_config', models.JSONField(blank=True, default=dict, verbose_name='原始配置')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='scanner.lxc', verbose_name='所属容器')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': 'LXC配置',
                'verbose_name_plural': 'LXC配置',
                'ordering': ['container'],
                'unique_together': {('container', 'scanned_at')},
            },
        ),
        migrations.CreateModel(
            name='VMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_type', models.CharField(blank=True, help_text='host / qemu65 / ...', max_length=64, verbose_name='CPU类型')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='CPU核心数')),
                ('cpu_sockets', models.IntegerField(blank=True, null=True, verbose_name='CPU插槽数')),
                ('memory_mb', models.IntegerField(blank=True, null=True, verbose_name='内存(MB)')),
                ('balloon_min_mb', models.IntegerField(blank=True, null=True, verbose_name='Balloon下限(MB)')),
                ('os_type', models.CharField(blank=True, max_length=64, verbose_name='系统类型')),
                ('boot_order', models.CharField(blank=True, max_length=256, verbose_name='启动顺序')),
                ('scsi_disks', models.JSONField(blank=True, default=list, help_text='[{"slot":"scsi0","storage":"local-lvm","size":"32G"}]', verbose_name='SCSI磁盘')),
                ('ide_disks', models.JSONField(blank=True, default=list, help_text='[{"slot":"ide0","storage":"local","file":"win10.iso","media":"cdrom"}]', verbose_name='IDE设备')),
                ('net_devices', models.JSONField(blank=True, default=list, help_text='[{"slot":"net0","model":"virtio","bridge":"vmbr0"}]', verbose_name='网卡')),
                ('agent_enabled', models.BooleanField(default=False, verbose_name='QEMU Agent')),
                ('ha_enabled', models.BooleanField(default=False, verbose_name='HA启用')),
                ('ha_group', models.CharField(blank=True, max_length=64, verbose_name='HA组')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('tags', models.CharField(blank=True, max_length=256, verbose_name='标签')),
                ('raw_config', models.JSONField(blank=True, default=dict, verbose_name='原始配置')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='scanner.vm', verbose_name='所属VM')),
            ],
            options={
                'verbose_name': 'VM配置',
                'verbose_name_plural': 'VM配置',
                'ordering': ['vm'],
                'unique_together': {('vm', 'scanned_at')},
            },
        ),
    ]
