# Generated by Django 5.0.14 on 2026-06-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_haresource_lxcconfig_vmconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='lxc',
            name='has_template',
            field=models.BooleanField(default=False, verbose_name='是否为模板'),
        ),
    ]
