# Generated by Django 5.0.14 on 2026-06-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_lxc_has_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lxc',
            unique_together={('node', 'vmid')},
        ),
        migrations.AlterUniqueTogether(
            name='lxcconfig',
            unique_together={('container',)},
        ),
        migrations.AlterUniqueTogether(
            name='vm',
            unique_together={('node', 'vmid')},
        ),
        migrations.AlterUniqueTogether(
            name='vmconfig',
            unique_together={('vm',)},
        ),
    ]
