# Generated by Django 5.0.14 on 2026-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_alter_lxc_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='bond_mode',
            field=models.CharField(blank=True, help_text='balance-rr / 802.3ad / balance-xor / ...', max_length=32, verbose_name='Bond模式'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='bond_slaves',
            field=models.CharField(blank=True, help_text='bond 包含的物理端口，如 eno1 eno2', max_length=256, verbose_name='Bond从接口'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='bridge_ports',
            field=models.CharField(blank=True, help_text='bridge 包含的物理端口，如 eno1 eno2', max_length=256, verbose_name='Bridge端口'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='mtu',
            field=models.IntegerField(blank=True, null=True, verbose_name='MTU'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='vlan_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='VLAN ID'),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='type',
            field=models.CharField(help_text='eth / bond / bridge / vlan', max_length=32, verbose_name='类型'),
        ),
    ]
