# Generated by Django 4.2.30 on 2026-07-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0003_agent_cluster_set_null'),
        ('clusters', '0003_pve_fields_required'),
        ('scanner', '0006_networkinterface_bond_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDNZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(db_index=True, max_length=64, verbose_name='区域名')),
                ('zone_type', models.CharField(blank=True, help_text='vlan / vxlan / qinq / ...', max_length=32, verbose_name='类型')),
                ('nodes', models.CharField(blank=True, help_text='关联节点列表', max_length=256, verbose_name='节点')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdn_zones', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': 'SDN区域',
                'verbose_name_plural': 'SDN区域',
                'ordering': ['zone'],
                'unique_together': {('cluster', 'zone')},
            },
        ),
        migrations.CreateModel(
            name='SDNVNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnet', models.CharField(db_index=True, max_length=64, verbose_name='虚拟网络名')),
                ('vnet_type', models.CharField(blank=True, help_text='vlan / vxlan / ...', max_length=32, verbose_name='类型')),
                ('vlan', models.IntegerField(blank=True, null=True, verbose_name='VLAN ID')),
                ('zone_name', models.CharField(blank=True, max_length=64, verbose_name='区域名')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdn_vnets', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vnets', to='scanner.sdnzone', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': 'SDN虚拟网络',
                'verbose_name_plural': 'SDN虚拟网络',
                'ordering': ['vnet'],
                'unique_together': {('cluster', 'vnet')},
            },
        ),
        migrations.CreateModel(
            name='SDNSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(help_text='10.0.0.0/24', max_length=64, verbose_name='子网')),
                ('vnet_name', models.CharField(blank=True, max_length=64, verbose_name='虚拟网络名')),
                ('gateway', models.CharField(blank=True, max_length=64, verbose_name='网关')),
                ('dns_server', models.CharField(blank=True, max_length=128, verbose_name='DNS服务器')),
                ('dns_zone_prefix', models.CharField(blank=True, max_length=128, verbose_name='DNS区域前缀')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdn_subnets', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
                ('vnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='scanner.sdnvnet', verbose_name='所属虚拟网络')),
            ],
            options={
                'verbose_name': 'SDN子网',
                'verbose_name_plural': 'SDN子网',
                'ordering': ['subnet'],
                'unique_together': {('cluster', 'subnet')},
            },
        ),
    ]
