# Generated by Django 5.0.14 on 2026-07-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0003_agent_cluster_set_null'),
        ('scanner', '0007_sdnzone_sdnvnet_sdnsubnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapid', models.CharField(help_text='PVE 快照标识，如 snap1', max_length=128, verbose_name='快照ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='快照名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('snap_time', models.DateTimeField(blank=True, null=True, verbose_name='快照时间')),
                ('parent', models.CharField(blank=True, help_text='上一级快照标识，空表示根快照', max_length=128, verbose_name='父快照')),
                ('ram', models.BooleanField(default=False, help_text='创建快照时是否保存内存状态', verbose_name='保存内存')),
                ('vmstate', models.BooleanField(default=False, verbose_name='保存运行状态')),
                ('snap_type', models.CharField(blank=True, help_text='如 snapshot / qemu / vztmpl', max_length=32, verbose_name='快照类型')),
                ('size_mb', models.BigIntegerField(blank=True, null=True, verbose_name='快照大小(MB)')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='scanner.vm', verbose_name='所属VM')),
            ],
            options={
                'verbose_name': 'VM快照',
                'verbose_name_plural': 'VM快照',
                'ordering': ['-snap_time'],
                'unique_together': {('vm', 'snapid')},
            },
        ),
    ]
