# Generated by Django 5.0.14 on 2026-07-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0003_agent_cluster_set_null'),
        ('clusters', '0003_pve_fields_required'),
        ('scanner', '0008_add_vmsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='PVE 任务 UPID', max_length=128, verbose_name='任务ID')),
                ('vmid', models.IntegerField(blank=True, null=True, verbose_name='VM/CT ID')),
                ('resource_type', models.CharField(blank=True, help_text='vm / ct', max_length=16, verbose_name='资源类型')),
                ('node_name', models.CharField(blank=True, max_length=128, verbose_name='所在节点')),
                ('storage_name', models.CharField(blank=True, max_length=128, verbose_name='备份存储')),
                ('mode', models.CharField(blank=True, help_text='snapshot / suspend / stop', max_length=32, verbose_name='模式')),
                ('status', models.CharField(help_text='ok / error / running', max_length=32, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='备份大小(字节)')),
                ('filename', models.CharField(blank=True, max_length=512, verbose_name='文件名')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_histories', to='clusters.cluster', verbose_name='所属集群')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_histories', to='scanner.clusternode', verbose_name='所在节点')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '备份历史',
                'verbose_name_plural': '备份历史',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=128, verbose_name='存储名称')),
                ('storage_type', models.CharField(blank=True, help_text='local / nfs / cifs / pbs / ...', max_length=32, verbose_name='类型')),
                ('path', models.CharField(blank=True, max_length=512, verbose_name='路径')),
                ('content_types', models.CharField(blank=True, max_length=256, verbose_name='内容类型')),
                ('active', models.BooleanField(default=True, verbose_name='活跃')),
                ('shared', models.BooleanField(default=False, verbose_name='共享')),
                ('total_gb', models.BigIntegerField(blank=True, null=True, verbose_name='总容量(GB)')),
                ('used_gb', models.BigIntegerField(blank=True, null=True, verbose_name='已用(GB)')),
                ('avail_gb', models.BigIntegerField(blank=True, null=True, verbose_name='可用(GB)')),
                ('used_fraction', models.FloatField(blank=True, null=True, verbose_name='使用率')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_storages', to='clusters.cluster', verbose_name='所属集群')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_storages', to='scanner.clusternode', verbose_name='所属节点')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '备份存储',
                'verbose_name_plural': '备份存储',
                'ordering': ['cluster', 'storage_name'],
            },
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='PVE 备份任务标识，如 vzdump-100-xxx', max_length=128, verbose_name='任务ID')),
                ('vmid', models.IntegerField(blank=True, null=True, verbose_name='VM/CT ID')),
                ('resource_type', models.CharField(blank=True, help_text='vm / ct / all', max_length=16, verbose_name='资源类型')),
                ('node_name', models.CharField(blank=True, max_length=128, verbose_name='所在节点')),
                ('storage_name', models.CharField(blank=True, max_length=128, verbose_name='备份存储')),
                ('mode', models.CharField(blank=True, help_text='snapshot / suspend / stop', max_length=32, verbose_name='模式')),
                ('schedule', models.CharField(blank=True, help_text="cron 表达式，如 '02:00'", max_length=128, verbose_name='调度规则')),
                ('retention', models.CharField(blank=True, help_text='keep-last=3, keep-daily=7, ...', max_length=64, verbose_name='保留策略')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('compress', models.CharField(blank=True, help_text='zstd / lzo / gzip / 0', max_length=32, verbose_name='压缩')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次执行')),
                ('last_status', models.CharField(blank=True, help_text='ok / error', max_length=32, verbose_name='上次状态')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='下次执行')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='clusters.cluster', verbose_name='所属集群')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='scanner.clusternode', verbose_name='所在节点')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '备份任务',
                'verbose_name_plural': '备份任务',
                'ordering': ['cluster', 'job_id'],
                'unique_together': {('cluster', 'job_id')},
            },
        ),
    ]
