# Generated by Django 5.0.14 on 2026-07-03 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0003_agent_cluster_set_null'),
        ('clusters', '0003_pve_fields_required'),
        ('scanner', '0009_add_backup_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, help_text='PVE 复制任务标识，如 1-0', max_length=128, verbose_name='任务ID')),
                ('vmid', models.IntegerField(blank=True, null=True, verbose_name='VM/CT ID')),
                ('resource_type', models.CharField(blank=True, help_text='vm / ct', max_length=16, verbose_name='资源类型')),
                ('source_node', models.CharField(blank=True, max_length=128, verbose_name='源节点')),
                ('target_node', models.CharField(blank=True, max_length=128, verbose_name='目标节点')),
                ('schedule', models.CharField(blank=True, help_text='如 */15 (每15分钟)', max_length=128, verbose_name='调度规则')),
                ('rate_limit', models.IntegerField(blank=True, null=True, verbose_name='速率限制(MB/s)')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('state', models.CharField(blank=True, help_text='active / disabled / error / syncing', max_length=32, verbose_name='状态')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='上次同步时间')),
                ('last_try', models.DateTimeField(blank=True, null=True, verbose_name='上次尝试时间')),
                ('last_duration', models.IntegerField(blank=True, null=True, verbose_name='上次同步耗时(秒)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('sync_count', models.IntegerField(default=0, verbose_name='成功同步次数')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replication_jobs', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '复制任务',
                'verbose_name_plural': '复制任务',
                'ordering': ['cluster', 'job_id'],
                'unique_together': {('cluster', 'job_id')},
            },
        ),
    ]
