# Generated by Django 5.0.14 on 2026-07-03 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0003_agent_cluster_set_null'),
        ('clusters', '0003_pve_fields_required'),
        ('scanner', '0010_replication_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallIPSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text='cluster / vm', max_length=16, verbose_name='作用域')),
                ('vmid', models.IntegerField(blank=True, null=True, verbose_name='VM/CT ID')),
                ('name', models.CharField(help_text='如 management / blacklist', max_length=64, verbose_name='IPSet名称')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_ipsets', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '防火墙IPSet',
                'verbose_name_plural': '防火墙IPSet',
                'ordering': ['name'],
                'unique_together': {('cluster', 'scope', 'vmid', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FirewallAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text='cluster / vm', max_length=16, verbose_name='作用域')),
                ('vmid', models.IntegerField(blank=True, null=True, verbose_name='VM/CT ID')),
                ('name', models.CharField(max_length=64, verbose_name='别名')),
                ('cidr', models.CharField(blank=True, help_text='如 192.168.1.0/24 或 10.0.0.1', max_length=128, verbose_name='IP/CIDR')),
                ('alias_type', models.CharField(help_text='ip / net / mac', max_length=16, verbose_name='类型')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_aliases', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '防火墙别名',
                'verbose_name_plural': '防火墙别名',
                'ordering': ['name'],
                'unique_together': {('cluster', 'scope', 'vmid', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FirewallIPSetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='如 192.168.1.0/24', max_length=64, verbose_name='IP/CIDR')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('nomatch', models.BooleanField(default=False, verbose_name='反向匹配')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('ipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scanner.firewallipset', verbose_name='所属IPSet')),
            ],
            options={
                'verbose_name': 'IPSet条目',
                'verbose_name_plural': 'IPSet条目',
                'ordering': ['cidr'],
                'unique_together': {('ipset', 'cidr')},
            },
        ),
        migrations.CreateModel(
            name='FirewallOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text='cluster / node / vm / ct', max_length=16, verbose_name='作用域')),
                ('node_name', models.CharField(blank=True, max_length=128, verbose_name='节点名称')),
                ('vmid', models.IntegerField(blank=True, null=True, verbose_name='VM/CT ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用防火墙')),
                ('policy_in', models.CharField(default='ACCEPT', help_text='ACCEPT / DROP / REJECT', max_length=16, verbose_name='入站策略')),
                ('policy_out', models.CharField(default='ACCEPT', max_length=16, verbose_name='出站策略')),
                ('policy_forward', models.CharField(default='ACCEPT', help_text='仅 nftables 支持 forward 规则', max_length=16, verbose_name='转发策略')),
                ('log_level_in', models.CharField(blank=True, help_text='nolog / info / warning / err / crit', max_length=16, verbose_name='入站日志级别')),
                ('log_level_out', models.CharField(blank=True, max_length=16, verbose_name='出站日志级别')),
                ('dhcp', models.BooleanField(default=False, verbose_name='DHCP')),
                ('ipfilter', models.BooleanField(default=False, verbose_name='IP过滤')),
                ('ndp', models.BooleanField(default=False, verbose_name='NDP')),
                ('macfilter', models.BooleanField(default=False, verbose_name='MAC过滤')),
                ('raw_options', models.JSONField(blank=True, default=dict, verbose_name='原始选项')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_options', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '防火墙选项',
                'verbose_name_plural': '防火墙选项',
                'ordering': ['scope', 'node_name', 'vmid'],
                'unique_together': {('cluster', 'scope', 'node_name', 'vmid')},
            },
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text='cluster / node / vm / ct / group', max_length=16, verbose_name='作用域')),
                ('group_name', models.CharField(blank=True, max_length=64, verbose_name='安全组名')),
                ('node_name', models.CharField(blank=True, max_length=128, verbose_name='节点名称')),
                ('vmid', models.IntegerField(blank=True, null=True, verbose_name='VM/CT ID')),
                ('pos', models.IntegerField(default=0, verbose_name='规则位置')),
                ('action', models.CharField(help_text='ACCEPT / DROP / REJECT', max_length=16, verbose_name='动作')),
                ('direction', models.CharField(help_text='in / out / forward', max_length=8, verbose_name='方向')),
                ('proto', models.CharField(blank=True, help_text='tcp / udp / icmp', max_length=16, verbose_name='协议')),
                ('source', models.CharField(blank=True, max_length=128, verbose_name='源地址')),
                ('dest', models.CharField(blank=True, max_length=128, verbose_name='目标地址')),
                ('dport', models.CharField(blank=True, max_length=128, verbose_name='目标端口')),
                ('sport', models.CharField(blank=True, max_length=128, verbose_name='源端口')),
                ('comment', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('log', models.CharField(blank=True, help_text='nolog / info / warning / err / crit', max_length=16, verbose_name='日志')),
                ('iface', models.CharField(blank=True, max_length=32, verbose_name='接口')),
                ('macro', models.CharField(blank=True, max_length=64, verbose_name='宏')),
                ('raw_rule', models.JSONField(blank=True, default=dict, verbose_name='原始规则')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '防火墙规则',
                'verbose_name_plural': '防火墙规则',
                'ordering': ['scope', 'node_name', 'vmid', 'pos'],
                'unique_together': {('cluster', 'scope', 'node_name', 'vmid', 'group_name', 'pos')},
            },
        ),
    ]
