# Generated by Django 5.0.14 on 2026-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_firewall_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusternode',
            name='cpu_family',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU代号'),
        ),
        migrations.AddField(
            model_name='clusternode',
            name='cpu_flags',
            field=models.TextField(blank=True, help_text='空格分隔的 CPU feature flags', verbose_name='CPU特性标志'),
        ),
        migrations.AddField(
            model_name='clusternode',
            name='cpu_hvm',
            field=models.BooleanField(default=False, help_text='VT-x (Intel) 或 AMD-V', verbose_name='硬件虚拟化'),
        ),
        migrations.AddField(
            model_name='clusternode',
            name='cpu_mhz',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU频率(MHz)'),
        ),
        migrations.AddField(
            model_name='clusternode',
            name='cpu_vendor',
            field=models.CharField(blank=True, help_text='GenuineIntel / AuthenticAMD', max_length=64, verbose_name='CPU厂商'),
        ),
    ]
