# Generated by Django 5.0.14 on 2026-07-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0004_agentevent'),
        ('clusters', '0005_add_sync_fields'),
        ('scanner', '0012_add_cpu_structured_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField(help_text='PVE 日志序号 (n 字段)', verbose_name='日志序号')),
                ('log_level', models.CharField(blank=True, help_text='info / warning / err', max_length=16, verbose_name='日志级别')),
                ('tag', models.CharField(blank=True, help_text='cluster / corosync / ha / ...', max_length=64, verbose_name='日志标签')),
                ('message', models.TextField(blank=True, verbose_name='日志内容')),
                ('log_time', models.DateTimeField(blank=True, null=True, verbose_name='日志时间')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_logs', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '集群日志',
                'verbose_name_plural': '集群日志',
                'ordering': ['-log_time'],
                'indexes': [models.Index(fields=['cluster', '-log_time'], name='scanner_clu_cluster_5e3da0_idx'), models.Index(fields=['cluster', 'log_level'], name='scanner_clu_cluster_2b8c5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClusterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upid', models.CharField(help_text='PVE 唯一任务标识', max_length=128, verbose_name='任务 UPID')),
                ('task_type', models.CharField(blank=True, help_text='qmigrate / vzdump / hamigrate / ha-fencing / ...', max_length=64, verbose_name='任务类型')),
                ('status', models.CharField(blank=True, help_text='OK / running / ...', max_length=32, verbose_name='状态')),
                ('exit_status', models.CharField(blank=True, max_length=32, verbose_name='退出状态')),
                ('node_name', models.CharField(blank=True, max_length=128, verbose_name='执行节点')),
                ('user', models.CharField(blank=True, max_length=128, verbose_name='触发用户')),
                ('vmid', models.IntegerField(blank=True, null=True, verbose_name='VM/CT ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('scanned_at', models.DateTimeField(db_index=True, verbose_name='扫描时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_tasks', to='clusters.cluster', verbose_name='所属集群')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_api.scantask')),
            ],
            options={
                'verbose_name': '集群任务',
                'verbose_name_plural': '集群任务',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['cluster', '-start_time'], name='scanner_clu_cluster_5c73f4_idx'), models.Index(fields=['cluster', 'task_type'], name='scanner_clu_cluster_d2da52_idx')],
            },
        ),
    ]
