# Generated by Django 5.0.14 on 2026-07-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0005_add_sync_fields'),
        ('scanner', '0013_add_cluster_task_and_cluster_log'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clusterlog',
            unique_together={('cluster', 'entry_id', 'log_time')},
        ),
        migrations.AlterUniqueTogether(
            name='clustertask',
            unique_together={('cluster', 'upid')},
        ),
    ]
