# Generated by Django 5.0.14 on 2026-07-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_alter_clusterlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusternode',
            name='cpu_load',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU负载(%)'),
        ),
        migrations.AlterField(
            model_name='lxc',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU使用率(%)'),
        ),
        migrations.AlterField(
            model_name='vm',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU使用率(%)'),
        ),
    ]
