# Generated by Django 5.0.14 on 2026-06-30 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='用户名')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '退出登录'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('change_password', '修改密码'), ('reset_password', '重置密码'), ('register', '注册'), ('other', '其他')], db_index=True, max_length=32, verbose_name='操作类型')),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, max_length=64, verbose_name='资源 ID')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
