# Generated by Django 5.0.14 on 2026-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='scan_interval_minutes',
            field=models.IntegerField(default=5, verbose_name='Agent扫描间隔(分钟)'),
        ),
    ]
