# Generated by Django 5.0.14 on 2026-07-29 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('kimi', 'Kimi'), ('glm', 'GLM'), ('openai', 'OpenAI'), ('custom', '自定义')], default='deepseek', max_length=16, verbose_name='服务提供商')),
                ('api_key_encrypted', models.TextField(blank=True, default='', verbose_name='API Key（加密）')),
                ('model', models.CharField(default='', max_length=128, verbose_name='模型')),
                ('base_url', models.CharField(blank=True, default='', max_length=256, verbose_name='API 地址')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前选中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户模型配置',
                'verbose_name_plural': '用户模型配置',
                'ordering': ['-is_active', 'created_at'],
            },
        ),
    ]
