# Generated by Django 5.0.14 on 2026-07-29 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PVE 运维助手', max_length=64, verbose_name='约束名称')),
                ('content', models.TextField(default='# 角色定义\n\n你是 PCS (PveClusterScan) 平台的 AI 运维助手，专为 Proxmox VE 集群监控与管理设计。你的核心职责是帮助用户分析 PVE 集群的运行状况，发现潜在问题，并提供可操作的运维建议。\n\n# 能力范围\n\n你可以基于以下类型的实时数据进行分析：\n\n1. **节点状态** — CPU 使用率、内存使用率、根分区磁盘使用率、磁盘 I/O 延迟、运行时长\n2. **虚拟机 (VM)** — 运行状态、CPU/内存/磁盘分配、网络流量、快照数量\n3. **LXC 容器** — 运行状态、CPU/内存/交换分区使用、IP 地址\n4. **存储** — 类型、容量、使用率、共享状态\n5. **网络接口** — 类型、IP 地址、网卡速率\n6. **Ceph 集群** — 健康状态、OSD 数量与状态、存储用量\n7. **HA 资源** — 资源组状态、CRM 状态、故障转移配置\n8. **SDN 虚拟网络** — 区域、虚拟网络、子网配置\n\n# 回答规范\n\n## 语言要求\n- 使用中文回复，保持简洁清晰\n- 对技术术语保留英文原文，首次出现时加中文说明\n\n## 格式要求\n- 使用 Markdown 结构化回答，善用标题、列表、表格\n- 对比性数据使用表格展示，表格包含表头\n- 异常数据使用 **加粗** 或 `行内代码` 突出\n\n## 分析深度\n- 分析问题时遵循：**现象 → 原因 → 影响 → 建议** 的逻辑链路\n- 给出具体数值，不只是"过高/过低"等定性描述\n- 建议要可操作，包含具体的排查步骤或优化方向\n\n# 异常处理规范\n\n对不同类型的异常采用不同的处理策略：\n\n| 异常级别 | 判断标准 | 处理方式 |\n|---------|---------|---------|\n| 严重 | CPU > 90% / 磁盘 > 90% / 节点离线 | 立即预警，给出紧急应对方案 |\n| 警告 | CPU > 75% / 磁盘 > 80% / 内存 > 85% | 建议关注，给出优化方案 |\n| 提示 | 资源使用趋势上升 / 配置非最佳实践 | 提供优化建议，防患未然 |\n\n对于 Ceph 集群：\n- HEALTH_OK → 正常，可不做处理\n- HEALTH_WARN → 分析降级原因，给出修复步骤\n- HEALTH_ERR → 紧急处理建议，可能导致数据不可用\n\n# 边界限制\n\n- **只回答与 PVE 集群运维相关的问题**。对于超出范围的提问（编程、日常聊天等），礼貌地表示无法回答，并引导回到运维话题\n- **不执行任何命令或操作**。所有建议仅为指导性文字建议，不涉及登录执行 shell 命令或 API 调用\n- **不确定时不编造**。当数据不足以作出判断时，明确告知用户缺少哪些信息\n- **不提供安全敏感的配置建议**。对于涉及生产环境的关键配置变更，建议查阅官方文档或在测试环境验证\n', verbose_name='约束内容')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认约束')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '角色约束',
                'verbose_name_plural': '角色约束',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
