# Generated by Django 5.0.14 on 2026-07-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersystemprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userllmconfig',
            name='billing_mode',
            field=models.CharField(blank=True, choices=[('payg', '余额计费'), ('plan', 'Token Plan（套餐）')], default='', max_length=8, verbose_name='计费方式'),
        ),
        migrations.AlterField(
            model_name='userllmconfig',
            name='provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('kimi', 'Kimi'), ('glm', 'GLM'), ('openai', 'OpenAI'), ('mimo', 'MiMo（小米）'), ('custom', '自定义')], default='deepseek', max_length=16, verbose_name='服务提供商'),
        ),
    ]
