# Generated by Django 5.0.14 on 2026-07-30 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userllmconfig_billing_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userllmconfig',
            name='user',
            field=models.ForeignKey(blank=True, help_text='留空表示全局通用配置', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
