# Generated by Django 5.0.14 on 2026-06-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, help_text='Agent自生成唯一标识 (如 hostname+pid)', max_length=64, unique=True, verbose_name='Agent ID')),
                ('version', models.CharField(max_length=32, verbose_name='Agent版本')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('platform', models.CharField(blank=True, help_text='Linux x86_64 / Darwin arm64 / ...', max_length=64, verbose_name='平台')),
                ('python_version', models.CharField(blank=True, max_length=32, verbose_name='Python版本')),
                ('pve_api_endpoint', models.CharField(blank=True, help_text='如: https://192.168.1.100:8006', max_length=256, verbose_name='PVE API地址')),
                ('scan_interval', models.IntegerField(default=3600, verbose_name='扫描间隔(秒)')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '错误'), ('paused', '暂停')], default='online', max_length=32, verbose_name='状态')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('last_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='最后扫描时间')),
                ('current_task', models.CharField(blank=True, help_text='当前正在执行的任务类型', max_length=64, verbose_name='当前任务')),
                ('total_scans', models.IntegerField(default=0, verbose_name='总扫描次数')),
                ('failed_scans', models.IntegerField(default=0, verbose_name='失败次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='启动时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='clusters.cluster', verbose_name='所属集群')),
            ],
            options={
                'verbose_name': 'Agent实例',
                'verbose_name_plural': 'Agent实例',
                'ordering': ['-last_heartbeat_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(default='full_scan', help_text='full_scan / quick_scan / health_check / ...', max_length=64, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('partial', '部分成功')], default='running', max_length=32, verbose_name='状态')),
                ('total_nodes', models.IntegerField(default=0, verbose_name='节点数')),
                ('total_vms', models.IntegerField(default=0, verbose_name='虚拟机数')),
                ('total_lxc', models.IntegerField(default=0, verbose_name='容器数')),
                ('total_storages', models.IntegerField(default=0, verbose_name='存储数')),
                ('raw_data_size_kb', models.IntegerField(blank=True, null=True, verbose_name='原始数据大小(KB)')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Agent上报的完整JSON数据', verbose_name='原始数据')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='agent_api.agentinstance', verbose_name='Agent')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_tasks', to='clusters.cluster', verbose_name='集群')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['cluster', '-started_at'], name='agent_api_s_cluster_d1c7a9_idx')],
            },
        ),
    ]
