# Generated by Django 4.2.30 on 2026-06-30 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_pve_fields_required'),
        ('agent_api', '0002_alter_scantask_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinstance',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='clusters.cluster', verbose_name='所属集群'),
        ),
    ]
