# Generated by Django 5.0.14 on 2026-07-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0003_agent_cluster_set_null'),
        ('clusters', '0004_alter_cluster_unique_together_remove_cluster_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('register', '注册'), ('scan_upload', '扫描上报'), ('scan_failed', '扫描失败'), ('version_upgrade', '版本升级'), ('status_change', '状态变更'), ('error', '错误'), ('unregister', '卸载'), ('deactivated', '集群停用'), ('cluster_deleted', '集群删除')], max_length=32, verbose_name='事件类型')),
                ('version', models.CharField(blank=True, max_length=32, verbose_name='当前版本')),
                ('old_version', models.CharField(blank=True, max_length=32, verbose_name='旧版本')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agent_api.agentinstance', verbose_name='Agent')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.cluster', verbose_name='集群')),
            ],
            options={
                'verbose_name': 'Agent事件',
                'verbose_name_plural': 'Agent事件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cluster', '-created_at'], name='agent_api_a_cluster_6458eb_idx'), models.Index(fields=['agent', '-created_at'], name='agent_api_a_agent_i_e7fd49_idx'), models.Index(fields=['event_type', '-created_at'], name='agent_api_a_event_t_c11377_idx')],
            },
        ),
    ]
