# Generated by Django 5.0.14 on 2026-06-28 16:08

import apps.clusters.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='集群名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('agent_token', models.CharField(db_index=True, default=apps.clusters.models.generate_agent_token, max_length=64, unique=True, verbose_name='Agent令牌')),
                ('status', models.CharField(choices=[('pending', '待激活'), ('active', '活跃'), ('error', '错误'), ('archived', '已归档')], default='pending', max_length=32, verbose_name='状态')),
                ('pve_version', models.CharField(blank=True, max_length=64, verbose_name='PVE版本')),
                ('cluster_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='集群ID')),
                ('total_nodes', models.IntegerField(default=0, verbose_name='节点总数')),
                ('total_vms', models.IntegerField(default=0, verbose_name='虚拟机总数')),
                ('total_lxc', models.IntegerField(default=0, verbose_name='容器总数')),
                ('total_storage', models.IntegerField(default=0, verbose_name='存储总数')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='最后扫描时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '集群',
                'verbose_name_plural': '集群',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
