# Generated by Django 5.0.14 on 2026-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='pve_endpoint',
            field=models.CharField(blank=True, help_text='如 https://192.168.1.200:8006', max_length=256, verbose_name='PVE API 地址'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='pve_token',
            field=models.CharField(blank=True, help_text='如 root@pam!monitor:xxxxxxxxxxxx', max_length=256, verbose_name='PVE API Token'),
        ),
    ]
