# Generated by Django 5.0.14 on 2026-06-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_add_pve_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='pve_endpoint',
            field=models.CharField(help_text='如 https://192.168.1.200:8006', max_length=256, verbose_name='PVE API 地址'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='pve_token',
            field=models.CharField(help_text='如 root@pam!monitor:xxxxxxxxxxxx', max_length=256, verbose_name='PVE API Token'),
        ),
    ]
