# Generated by Django 5.0.14 on 2026-07-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_pve_fields_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='user',
        ),
    ]
