# Generated by Django 5.0.14 on 2026-07-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_alter_cluster_unique_together_remove_cluster_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='sync_enabled',
            field=models.BooleanField(default=False, verbose_name='启用数据同步'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='sync_id',
            field=models.CharField(blank=True, db_index=True, help_text='PCSS 分配的集群同步标识', max_length=64, verbose_name='同步ID'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='sync_token',
            field=models.CharField(blank=True, help_text='PCSS 分配的同步认证令牌', max_length=128, verbose_name='同步Token'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='sync_url',
            field=models.URLField(blank=True, help_text='PCSS 平台地址，如 https://pcss.example.com', max_length=512, verbose_name='同步目标地址'),
        ),
    ]
